using DerotMyBrain.Core.Entities;
using Xunit;

namespace DerotMyBrain.Tests.Units.Entities;

public class SourceTests
{
    [Fact]
    public void Constructor_ShouldInitializeDefaults()
    {
        // Arrange & Act
        var source = new Source();

        // Assert
        // Id is not auto-generated by Guid usually for Source (it uses hash), let's check its default
        Assert.Equal(string.Empty, source.Id); 
        Assert.Equal(string.Empty, source.UserId);
        Assert.Equal(string.Empty, source.ExternalId);
        Assert.False(source.IsTracked);
        Assert.Empty(source.Activities);
    }

    [Fact]
    public void Properties_ShouldStoreValues()
    {
        // Arrange
        var source = new Source
        {
            Id = "hash123",
            UserId = "user1",
            Type = SourceType.Wikipedia,
            ExternalId = "wiki_page",
            DisplayTitle = "Wiki Page",
            Url = "http://wiki.com",
            IsTracked = true
        };

        // Assert
        Assert.Equal("hash123", source.Id);
        Assert.Equal("user1", source.UserId);
        Assert.Equal(SourceType.Wikipedia, source.Type);
        Assert.True(source.IsTracked);
    }
}
