// <auto-generated />
using System;
using DerotMyBrain.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DerotMyBrain.API.Migrations
{
    [DbContext(typeof(DerotDbContext))]
    [Migration("20260119235344_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DerotMyBrain.API.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastConnectionAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DerotMyBrain.API.Models.UserActivity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("BestScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstAttemptDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTracked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastAttemptDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LlmModelName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LlmVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WikipediaUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsTracked")
                        .HasDatabaseName("idx_activities_tracked");

                    b.HasIndex("UserId", "LastAttemptDate")
                        .HasDatabaseName("idx_activities_user_date");

                    b.HasIndex("UserId", "Type")
                        .HasDatabaseName("idx_activities_type");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("DerotMyBrain.API.Models.UserPreferences", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("auto");

                    b.Property<string>("PreferredTheme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("derot-brain");

                    b.Property<int>("QuestionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10);

                    b.Property<string>("SelectedCategories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("DerotMyBrain.API.Models.UserActivity", b =>
                {
                    b.HasOne("DerotMyBrain.API.Models.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DerotMyBrain.API.Models.UserPreferences", b =>
                {
                    b.HasOne("DerotMyBrain.API.Models.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("DerotMyBrain.API.Models.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DerotMyBrain.API.Models.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
