// <auto-generated />
using System;
using DerotMyBrain.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DerotMyBrain.API.Migrations
{
    [DbContext(typeof(DerotDbContext))]
    [Migration("20260121182750_ReshapeActivitiesAndAddTrackedTopics")]
    partial class ReshapeActivitiesAndAddTrackedTopics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DerotMyBrain.API.Models.TrackedTopic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BestScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BestScoreDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirstAttemptDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirstReadDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAttemptDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastReadDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalQuestions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalQuizAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalReadSessions")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TrackedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WikipediaUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "BestScore")
                        .HasDatabaseName("IX_TrackedTopic_UserId_BestScore");

                    b.HasIndex("UserId", "LastAttemptDate")
                        .HasDatabaseName("IX_TrackedTopic_UserId_LastAttemptDate");

                    b.HasIndex("UserId", "Topic")
                        .IsUnique()
                        .HasDatabaseName("IX_TrackedTopic_UserId_Topic_Unique");

                    b.ToTable("TrackedTopics");
                });

            modelBuilder.Entity("DerotMyBrain.API.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastConnectionAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DerotMyBrain.API.Models.UserActivity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("LlmModelName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LlmVersion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalQuestions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Read");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WikipediaUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SessionDate")
                        .HasDatabaseName("IX_UserActivity_UserId_SessionDate");

                    b.HasIndex("UserId", "Topic", "SessionDate")
                        .HasDatabaseName("IX_UserActivity_UserId_Topic_SessionDate");

                    b.HasIndex("UserId", "Type", "SessionDate")
                        .HasDatabaseName("IX_UserActivity_UserId_Type_SessionDate");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("DerotMyBrain.API.Models.UserPreferences", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("auto");

                    b.Property<string>("PreferredTheme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("derot-brain");

                    b.Property<int>("QuestionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10);

                    b.Property<string>("SelectedCategories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("DerotMyBrain.API.Models.TrackedTopic", b =>
                {
                    b.HasOne("DerotMyBrain.API.Models.User", "User")
                        .WithMany("TrackedTopics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DerotMyBrain.API.Models.UserActivity", b =>
                {
                    b.HasOne("DerotMyBrain.API.Models.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DerotMyBrain.API.Models.UserPreferences", b =>
                {
                    b.HasOne("DerotMyBrain.API.Models.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("DerotMyBrain.API.Models.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DerotMyBrain.API.Models.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Preferences");

                    b.Navigation("TrackedTopics");
                });
#pragma warning restore 612, 618
        }
    }
}
