// <auto-generated />
using System;
using DerotMyBrain.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DerotMyBrain.Infrastructure.Migrations
{
    [DbContext(typeof(DerotDbContext))]
    [Migration("20260126185508_AddSessionAndSourceModel")]
    partial class AddSessionAndSourceModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DerotMyBrain.Core.Entities.Source", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastConnectionAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.UserActivity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArticleContent")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BacklogAddsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExploreDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBaseline")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNewBestScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LlmModelName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LlmVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuizDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReadDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultingReadActivityId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ScorePercentage")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("SessionDateEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SessionDateStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserSessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResultingReadActivityId");

                    b.HasIndex("UserSessionId");

                    b.HasIndex("UserId", "SessionDateEnd");

                    b.HasIndex("UserId", "SessionDateStart");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.UserFocus", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("BestScore")
                        .HasColumnType("REAL");

                    b.Property<string>("DisplayTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastAttemptDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("LastScore")
                        .HasColumnType("REAL");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalQuizTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalReadTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalStudyTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("UserId");

                    b.ToTable("FocusAreas", (string)null);
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.UserPreferences", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultDifficulty")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "defaultDifficulty");

                    b.Property<string>("FavoriteCategories")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "selectedCategories");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("en")
                        .HasAnnotation("Relational:JsonPropertyName", "language");

                    b.Property<int>("QuestionsPerQuiz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(5)
                        .HasAnnotation("Relational:JsonPropertyName", "questionCount");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("system")
                        .HasAnnotation("Relational:JsonPropertyName", "preferredTheme");

                    b.HasKey("UserId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.UserSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.UserActivity", b =>
                {
                    b.HasOne("DerotMyBrain.Core.Entities.UserActivity", "ResultingReadActivity")
                        .WithMany()
                        .HasForeignKey("ResultingReadActivityId");

                    b.HasOne("DerotMyBrain.Core.Entities.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DerotMyBrain.Core.Entities.UserSession", "UserSession")
                        .WithMany("Activities")
                        .HasForeignKey("UserSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResultingReadActivity");

                    b.Navigation("User");

                    b.Navigation("UserSession");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.UserFocus", b =>
                {
                    b.HasOne("DerotMyBrain.Core.Entities.Source", "Source")
                        .WithMany("UserFocuses")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DerotMyBrain.Core.Entities.User", "User")
                        .WithMany("FocusAreas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.UserPreferences", b =>
                {
                    b.HasOne("DerotMyBrain.Core.Entities.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("DerotMyBrain.Core.Entities.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.UserSession", b =>
                {
                    b.HasOne("DerotMyBrain.Core.Entities.Source", "Source")
                        .WithMany("Sessions")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DerotMyBrain.Core.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.Source", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("UserFocuses");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("FocusAreas");

                    b.Navigation("Preferences");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.UserSession", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
