// <auto-generated />
using System;
using DerotMyBrain.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DerotMyBrain.Infrastructure.Migrations
{
    [DbContext(typeof(DerotDbContext))]
    partial class DerotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DerotMyBrain.Core.Entities.AppConfiguration", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("LLM")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppConfigurations");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.BacklogItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.HasIndex("UserId", "SourceId")
                        .IsUnique();

                    b.ToTable("BacklogItems");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.Document", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.HasIndex("UserId", "SourceId")
                        .IsUnique();

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.OnlineResource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.HasIndex("UserId", "SourceId")
                        .IsUnique();

                    b.ToTable("OnlineResources");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.Source", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ContentExtractionCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentExtractionError")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentExtractionStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInBacklog")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTracked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("TextContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("TopicId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserId");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.Topic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastConnectionAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.UserActivity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BacklogAddsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBaseline")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNewBestScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LlmModelName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LlmVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginExploreId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RefreshCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultingReadActivityId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ScorePercentage")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("SessionDateEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SessionDateStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserSessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResultingReadActivityId");

                    b.HasIndex("SourceId");

                    b.HasIndex("UserSessionId");

                    b.HasIndex("UserId", "SessionDateEnd");

                    b.HasIndex("UserId", "SessionDateStart");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.UserPreferences", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultDifficulty")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "defaultDifficulty");

                    b.Property<string>("FavoriteCategories")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "selectedCategories");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("en")
                        .HasAnnotation("Relational:JsonPropertyName", "language");

                    b.Property<int>("PreferredQuizFormat")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "preferredQuizFormat");

                    b.Property<int>("QuestionsPerQuiz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(5)
                        .HasAnnotation("Relational:JsonPropertyName", "questionCount");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("system")
                        .HasAnnotation("Relational:JsonPropertyName", "preferredTheme");

                    b.HasKey("UserId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.UserSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetSourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetTopicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TargetSourceId");

                    b.HasIndex("TargetTopicId");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.BacklogItem", b =>
                {
                    b.HasOne("DerotMyBrain.Core.Entities.Source", "Source")
                        .WithOne("BacklogItem")
                        .HasForeignKey("DerotMyBrain.Core.Entities.BacklogItem", "SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DerotMyBrain.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.Document", b =>
                {
                    b.HasOne("DerotMyBrain.Core.Entities.Source", "Source")
                        .WithOne("Document")
                        .HasForeignKey("DerotMyBrain.Core.Entities.Document", "SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DerotMyBrain.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.OnlineResource", b =>
                {
                    b.HasOne("DerotMyBrain.Core.Entities.Source", "Source")
                        .WithOne("OnlineResource")
                        .HasForeignKey("DerotMyBrain.Core.Entities.OnlineResource", "SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DerotMyBrain.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.Source", b =>
                {
                    b.HasOne("DerotMyBrain.Core.Entities.Topic", "Topic")
                        .WithMany("Sources")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DerotMyBrain.Core.Entities.User", "User")
                        .WithMany("Sources")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.Topic", b =>
                {
                    b.HasOne("DerotMyBrain.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.UserActivity", b =>
                {
                    b.HasOne("DerotMyBrain.Core.Entities.UserActivity", "ResultingReadActivity")
                        .WithMany()
                        .HasForeignKey("ResultingReadActivityId");

                    b.HasOne("DerotMyBrain.Core.Entities.Source", "Source")
                        .WithMany("Activities")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DerotMyBrain.Core.Entities.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DerotMyBrain.Core.Entities.UserSession", "UserSession")
                        .WithMany("Activities")
                        .HasForeignKey("UserSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResultingReadActivity");

                    b.Navigation("Source");

                    b.Navigation("User");

                    b.Navigation("UserSession");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.UserPreferences", b =>
                {
                    b.HasOne("DerotMyBrain.Core.Entities.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("DerotMyBrain.Core.Entities.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.UserSession", b =>
                {
                    b.HasOne("DerotMyBrain.Core.Entities.Source", "TargetSource")
                        .WithMany("Sessions")
                        .HasForeignKey("TargetSourceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DerotMyBrain.Core.Entities.Topic", "TargetTopic")
                        .WithMany()
                        .HasForeignKey("TargetTopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DerotMyBrain.Core.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetSource");

                    b.Navigation("TargetTopic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.Source", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("BacklogItem");

                    b.Navigation("Document");

                    b.Navigation("OnlineResource");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.Topic", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Preferences");

                    b.Navigation("Sessions");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.UserSession", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
