// <auto-generated />
using System;
using DerotMyBrain.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DerotMyBrain.Infrastructure.Migrations
{
    [DbContext(typeof(DerotDbContext))]
    partial class DerotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DerotMyBrain.Core.Entities.TrackedTopic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("BestScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BestScoreDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastInteraction")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalQuizAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalReadSessions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Title")
                        .IsUnique();

                    b.ToTable("TrackedTopics");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastConnectionAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.UserActivity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArticleContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentSourceType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTracked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastAttemptDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LlmModelName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LlmVersion")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payload")
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LastAttemptDate");

                    b.HasIndex("UserId", "Title", "LastAttemptDate");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.UserPreferences", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultDifficulty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FavoriteCategories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("en");

                    b.Property<int>("QuestionsPerQuiz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(5);

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("system");

                    b.HasKey("UserId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.TrackedTopic", b =>
                {
                    b.HasOne("DerotMyBrain.Core.Entities.User", "User")
                        .WithMany("TrackedTopics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.UserActivity", b =>
                {
                    b.HasOne("DerotMyBrain.Core.Entities.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.UserPreferences", b =>
                {
                    b.HasOne("DerotMyBrain.Core.Entities.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("DerotMyBrain.Core.Entities.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DerotMyBrain.Core.Entities.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Preferences");

                    b.Navigation("TrackedTopics");
                });
#pragma warning restore 612, 618
        }
    }
}
